disable other workflow

diff --git a/.github/workflows/apache-beam-dependency-problem.yml b/.github/workflows/apache-beam-dependency-problem.yml
--- a/.github/workflows/apache-beam-dependency-problem.yml
+++ b/.github/workflows/apache-beam-dependency-problem.yml
@@ -1,86 +1,86 @@
-name: count dependencies
-
-on:
-  push:
-  workflow_dispatch: {}
-
-jobs:
-  pure-java-linux-count-dependecies:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./apache-beam-dependency-problem
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'liberica'
-      - run: ./gradlew clean installDist
-      - name: show dependencies
-        run: ls -lah  build/install/apache-beam-dependency-problem/lib
-      - name: count dependencies
-        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
-      - name: "Check file existence linux"
-        id: check_files
-        uses: andstor/file-existence-action@v3.0.0
-        with:
-          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-core-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-harness-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-transform-service-launcher-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-grpc-1_54_0-0.1.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-guava-32_1_2-jre-0.1.jar"
-          fail: true
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
-
-  skdman-java-linux-count-dependecies:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./apache-beam-dependency-problem
-    steps:
-      - uses: actions/checkout@v4
-      - uses: renatoathaydes/setup-java-sdkman@main
-        with:
-          java-version: '21.0.1-librca' # The SDKMAN! JDK version to use.
-      - run: java -version
-      - run: ./gradlew clean installDist
-      - name: show dependencies
-        run: ls -lah  build/install/apache-beam-dependency-problem/lib
-      - name: count dependencies
-        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
-      - name: "Check file existence linux sdkman"
-        id: check_files
-        uses: andstor/file-existence-action@v3.0.0
-        with:
-          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-core-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-harness-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-transform-service-launcher-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-grpc-1_54_0-0.1.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-guava-32_1_2-jre-0.1.jar"
-          fail: true
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
-
-  mac-count-dependecies:
-    runs-on: macos-latest
-    defaults:
-      run:
-        working-directory: ./apache-beam-dependency-problem
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'liberica'
-      - run: ./gradlew clean installDist
-      - name: show dependencies
-        run: ls -lah  build/install/apache-beam-dependency-problem/lib
-      - name: count dependencies
-        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
-      - name: "Check file existence mac"
-        id: check_files
-        uses: andstor/file-existence-action@v3.0.0
-        with:
-          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-core-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-harness-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-transform-service-launcher-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-grpc-1_54_0-0.1.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-guava-32_1_2-jre-0.1.jar"
-          fail: true
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
+#name: count dependencies
+#
+#on:
+#  push:
+#  workflow_dispatch: {}
+#
+#jobs:
+#  pure-java-linux-count-dependecies:
+#    runs-on: ubuntu-latest
+#    defaults:
+#      run:
+#        working-directory: ./apache-beam-dependency-problem
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Set up JDK 21
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: '21'
+#          distribution: 'liberica'
+#      - run: ./gradlew clean installDist
+#      - name: show dependencies
+#        run: ls -lah  build/install/apache-beam-dependency-problem/lib
+#      - name: count dependencies
+#        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
+#      - name: "Check file existence linux"
+#        id: check_files
+#        uses: andstor/file-existence-action@v3.0.0
+#        with:
+#          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-core-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-harness-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-transform-service-launcher-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-grpc-1_54_0-0.1.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-guava-32_1_2-jre-0.1.jar"
+#          fail: true
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
+#
+#  skdman-java-linux-count-dependecies:
+#    runs-on: ubuntu-latest
+#    defaults:
+#      run:
+#        working-directory: ./apache-beam-dependency-problem
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: renatoathaydes/setup-java-sdkman@main
+#        with:
+#          java-version: '21.0.1-librca' # The SDKMAN! JDK version to use.
+#      - run: java -version
+#      - run: ./gradlew clean installDist
+#      - name: show dependencies
+#        run: ls -lah  build/install/apache-beam-dependency-problem/lib
+#      - name: count dependencies
+#        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
+#      - name: "Check file existence linux sdkman"
+#        id: check_files
+#        uses: andstor/file-existence-action@v3.0.0
+#        with:
+#          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-core-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-harness-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-transform-service-launcher-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-grpc-1_54_0-0.1.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-guava-32_1_2-jre-0.1.jar"
+#          fail: true
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
+#
+#  mac-count-dependecies:
+#    runs-on: macos-latest
+#    defaults:
+#      run:
+#        working-directory: ./apache-beam-dependency-problem
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Set up JDK 21
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: '21'
+#          distribution: 'liberica'
+#      - run: ./gradlew clean installDist
+#      - name: show dependencies
+#        run: ls -lah  build/install/apache-beam-dependency-problem/lib
+#      - name: count dependencies
+#        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
+#      - name: "Check file existence mac"
+#        id: check_files
+#        uses: andstor/file-existence-action@v3.0.0
+#        with:
+#          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-core-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-harness-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-sdks-java-transform-service-launcher-2.53.0.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-grpc-1_54_0-0.1.jar, ./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-vendor-guava-32_1_2-jre-0.1.jar"
+#          fail: true
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
